### ISSUE TITLE
Field 'teasertext' doesn't have a default value

### ISSUE THREAD

**Issue by t-schroeder** [ild-thl/moodle-local_isymeta#11]
Wenn man einen Kurs hat, bei dem in der DB `summary = NULL` steht und die editmetadata.php zu diesem Kurs öffnet, bekommt man den Fehler:

```
Field 'teasertext' doesn't have a default value
INSERT INTO mdl_ildmeta (coursetitle,starttime,courseid,lecturer,noindexcourse,overviewimage,detailimage,provider,subjectarea,courselanguage,processingtime,targetgroup,learninggoals,structure,detailslecturer,detailsmorelecturer,certificateofachievement,license,videocode,videolicense,exporttobird,shortname,coursetype,courseformat,selfpaced,audience,courseprerequisites,availablefrom,availableuntil) VALUES(...
```

Die folgende Zeile wird nie ausgeführt:

https://github.com/ild-thl/moodle-local_isymeta/blob/0f0262623193042457e8c2c2e7749ac815d8094c/edit_metadata.php#L365-L367

Einen Kurs mit `summary = NULL` kann man z.B. mit der Webservice-Funktion "core_course_create_courses" erzeugen.

**Comment by tinjohn** [comment]
pull request merged
