### ISSUE TITLE
Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by t-schroeder** [ild-thl/moodle-local_isymeta#12]
Beim ersten Aufrufen von edit_metadata.php tritt an der folgenden Stelle ein Fehler auf:

https://github.com/ild-thl/moodle-local_isymeta/blob/0f0262623193042457e8c2c2e7749ac815d8094c/edit_metadata.php#L413

Und zwar:

```
Fehler: mysqli::real_escape_string(): Argument #1 ($string) must be of type string, array given

Debug-Info: 
Error code: generalexceptionmessage×Diese Systemnachricht ablehnen

Stack trace: 
line 1140 of /lib/dml/mysqli_native_moodle_database.php: TypeError thrown
line 1140 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli->real_escape_string()
line 1352 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->emulate_bound_params()
line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 413 of /local/ildmeta/edit_metadata.php: call to mysqli_native_moodle_database->insert_record()
```

Verantwortlich für den Fehler ist diese Zeile:

https://github.com/ild-thl/moodle-local_isymeta/blob/0f0262623193042457e8c2c2e7749ac815d8094c/edit_metadata.php#L365-L367

`$toform->teasertext` sollte fürs Einfügen in die DB ein String sein und kein Array.

**Comment by tinjohn** [comment]
pull request merged

**Comment by tinjohn** [comment]
Fun Fact: Upgrading Moodle to 4.0.5 the unfixed version works again
